name: Teste de Workflow (Build e Publish ASP.NET WebAPI)
on:
  push:
    branches: [master]

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest
    steps:    
    - name: Step 1
      uses: actions/checkout@v2
      # Download dos arquivos da pasta raiz do repositório corrente (atual) do github

    - name: Docker Login    
      uses: docker/login-action@v3.2.0
      with:        
        username: 'rodrigocezarleao'
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build and push Docker images      
      uses: docker/build-push-action@v6.2.0
      with:
        context: .
        tags: 'rodrigocezarleao/pos-tech-fiap-ghactions-aspnet-api:latest'
        push: true
    
          
          
    
